[package]
name = "speedy_refs"
version = "0.2.3"
description = "A collection of simple, Fast, and light smart pointers for rust."
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]